[tool.poetry]
name = "hr-contact"
version = "0.1.0"
description = ""
authors = ["Dong Nguyen <dongd@greenglobal.vn>"]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.0.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
